twig:
    globals:
        locale: %locale%
        salon_url: %salon_url%
        book_pass_url: %book_pass_url%
        opened: true

oxygen_framework:
    templating:
        layouts:
            full: 'SSNTherapassBundle::layout.html.twig'
            light: 'SSNTherapassBundle::layout-light.html.twig'
            
oxygen_passbook:
    entities:
        event:
            class: SSN\TherapassBundle\Entity\Event
        event_product:
            class: SSN\TherapassBundle\Entity\EventProduct
        event_ticket:
            class: SSN\TherapassBundle\Entity\EventTicket

oxygen_weezevent:
      apikey: %weezevent_api_key%