parameters:
    oxygen_passbook.event_ticket.form.type_class: SSN\TherapassBundle\Form\Type\EventTicketFormType
    oxygen_passbook.event_ticket.form.model_class: SSN\TherapassBundle\Form\Model\EventTicketFormModel

twig:
    globals:
        locale: %locale%
        salon_url: %salon_url%
        book_pass_url: %book_pass_url%
        open_mode: %open_mode%
    form:
        resources:
            - 'SSNTherapassBundle::forms_template.html.twig'

oxygen_framework:
    templating:
        layouts:
            full: 'SSNTherapassBundle::layout.html.twig'
            light: 'SSNTherapassBundle::layout-light.html.twig'
            
oxygen_passbook:
    entities:
        event:
            class: SSN\TherapassBundle\Entity\Event
        event_product:
            class: SSN\TherapassBundle\Entity\EventProduct
        event_ticket:
            class: SSN\TherapassBundle\Entity\EventTicket
        event_product_slot:
            class: SSN\TherapassBundle\Entity\EventProductSlot

oxygen_weezevent:
      apikey: %weezevent_api_key%
      default:
          username: gilles.langellotti88@gmail.com
          password: salon2013