parameters:
    oxygen_passbook.event_ticket.form.type_class: SSN\TherapassBundle\Form\Type\EventTicketFormType
    oxygen_passbook.event_ticket.form.model_class: SSN\TherapassBundle\Form\Model\EventTicketFormModel
    oxygen_passbook.booking.form.model_class: SSN\TherapassBundle\Form\Model\BookingFormModel
    oxygen_passbook.form.booking.type_class: SSN\TherapassBundle\Form\Type\BookingFormType
    oxygen_passbook.booking.form.class: SSN\TherapassBundle\Form\Handler\BookingForm
    oxygen_passbook.event_product.form.type_class: SSN\TherapassBundle\Form\Type\EventProductFormType
    oxygen_passbook.event_product.form.model_class: SSN\TherapassBundle\Form\Model\EventProductFormModel
    oxygen_passbook.form.booking_person.type_class: SSN\TherapassBundle\Form\Type\BookingPersonFormType
    oxygen_passbook.booking_person.form.model_class: SSN\TherapassBundle\Form\Model\BookingPersonFormModel

twig:
    globals:
        locale: %locale%
        salon_url: %salon_url%
        book_pass_url: %book_pass_url%
        open_mode: %open_mode%
        passbook_url: %passbook_url%
        key_securisation: %secret%
    form:
        resources:
            - 'SSNTherapassBundle::forms_template.html.twig'

oxygen_framework:
    templating:
        layouts:
            full: 'SSNTherapassBundle::layout.html.twig'
            light: 'SSNTherapassBundle::layout-light.html.twig'
            
oxygen_passbook:
    # default types created with the app installation
    event_types: [care, conference, workshop_adult]
    entities:
        event:
            class: SSN\TherapassBundle\Entity\Event
            repository: SSN\TherapassBundle\Entity\Repository\EventRepository
        event_type:
            class: SSN\TherapassBundle\Entity\EventType
        event_product:
            class: SSN\TherapassBundle\Entity\EventProduct
            repository: SSN\TherapassBundle\Entity\Repository\EventProductRepository
        event_ticket:
            class: SSN\TherapassBundle\Entity\EventTicket
        event_product_slot:
            class: SSN\TherapassBundle\Entity\EventProductSlot
        booking_slot:
            class: SSN\TherapassBundle\Entity\BookingSlot
        booking_person:
            class: SSN\TherapassBundle\Entity\BookingPerson
            repository: SSN\TherapassBundle\Entity\Repository\BookingPersonRepository

oxygen_weezevent:
      apikey: %weezevent_api_key%
      default:
          username: gilles.langellotti88@gmail.com
          password: salon2013