imports:
    - { resource: config_dev.yml }
    - { resource: config-application.yml }
    
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                dbname:   %test_database_name%
                user:     %test_database_user%
                password: %test_database_password%
                charset:  UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
