ssn_public:
    resource: "@SSNTherapassBundle/Resources/config/routes/public.yml"
    prefix: /
ssn_admin:
    resource: "@SSNTherapassBundle/Resources/config/routes/admin.yml"
    prefix: /admin
ssn_security:
    resource: "@SSNTherapassBundle/Resources/config/routes/security.yml"
    prefix: /
    
oxygen_passbook_admin_event:
    resource: "@OxygenPassbookBundle/Resources/config/routes/event.yml"
    prefix: /admin
oxygen_passbook_admin_booking:
    resource: "@OxygenPassbookBundle/Resources/config/routes/booking-admin.yml"
    prefix: /admin
oxygen_passbook_admin_printing:
    resource: "@OxygenPassbookBundle/Resources/config/routes/printing-admin.yml"
    prefix: /admin   
    
ssn_therapass_booking:
    resource: "@SSNTherapassBundle/Resources/config/routes/booking.yml"
    prefix: /booking   