security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_BOOKER:      ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: exHwOy/y1cuvJlvc127qTMroIuFufhv1sDqIn+Ohp80ZfCzY3L0Wnl58j99iT2Hc5/9YoaLPNdli4VkjoCiFRw==, roles: [ 'ROLE_ADMIN' ] }
                    booker: { password: exHwOy/y1cuvJlvc127qTMroIuFufhv1sDqIn+Ohp80ZfCzY3L0Wnl58j99iT2Hc5/9YoaLPNdli4VkjoCiFRw==, roles: [ 'ROLE_BOOKER' ] }

    firewalls:
        booking_area:
            pattern:    ^/booking
            anonymous: ~ # Pour autoriser anonymous
            form_login:
                login_path:  ssn_therapass_login
                check_path:  ssn_therapass_login_check
                default_target_path: oxygen_passbook_event_list
            logout:
                path:   ssn_therapass_logout
                target: /
        admin_area:
            pattern:    ^/admin
            anonymous: ~ # Pour autoriser anonymous
            form_login:
                login_path:  ssn_therapass_admin_login
                check_path:  ssn_therapass_admin_login_check
                default_target_path: oxygen_passbook_booking_event_list
            logout:
                path:   ssn_therapass_admin_logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/print-bookings, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/booking, roles: ROLE_BOOKER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
